# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Build performance
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Headers for performance optimization
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache control for HTML (no cache, always revalidate)
    Cache-Control = "public, no-cache, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Long cache for hashed assets (1 year)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    # JavaScript files
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    # CSS files
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    # Font files
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

[[headers]]
  for = "/*.png"
  [headers.values]
    # Images
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    # Images
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    # SVG images
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  # Don't redirect if file exists
  conditions = {Role = ["Not", "admin"]}

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true